[tool.flit.metadata]
module = "tg"
dist-name = "tg"
description-file = "README.md"
author = "Paul Nameless"
author-email = "reacsdas@gmail.com"
home-page = 'https://github.com/paul-nameless/tg'
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
]
requires-python = ">=3.8"
requires = ['python-telegram==0.12.0']

[tool.flit.scripts]
tg = "tg.main:main"

[tool.black]
line-length = 79
