[tool.flit.metadata]
module = "tg"
dist-name = "tg"
description-file = "readme.md"
author = "Paul Nameless"
author-email = "reacsdas@gmail.com"
home-page = 'https://github.com/paul-nameless/tg'
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.8"
requires = ['python-telegram==0.14.0']

[tool.flit.scripts]
tg = "tg.__main__:main"

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
